name: china
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^1.3.3
  page_transition: ^1.1.4  
  sliding_up_panel: ^1.0.2
  youtube_player_flutter: ^6.1.0+7
  video_player: 
  url_launcher: ^5.7.10
  twinkle_button:
  http: 
  cached_network_image: 
  webview_flutter: 

  
 

  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  build_runner:

flutter_icons:
  image_path: "lib//icon/c1.png"
  android: true
  ios: true
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/china1.png
    - lib/assets/peking1.png
    - lib/assets/1.png
    - lib/assets/2.png
   
    - lib/assets/users.json
    - lib/assets/menschen1.png
    - lib/assets/geschichten1.png
    - lib/assets/peking2.png
    - lib/assets/peking3.png
    - lib/assets/peking4.png
    - lib/assets/peking5.png
    - lib/assets/peking6.png
    - lib/assets/peking7.png
    - lib/assets/peking8.png
    - lib/assets/peking9.png
    - lib/assets/peking10.png
    - lib/assets/peking11.png
    - lib/assets/hk1.png
    - lib/assets/tv.png
    - lib/assets/cn4.png
    - lib/assets/cn6.png
    - lib/assets/cn7.png
    - lib/assets/cn9.png
    - lib/assets/cn10.png
    - lib/assets/cn2.png
    - lib/assets/cn15.png
    - lib/assets/cn16.png
    - lib/assets/cn14.jpg
    - lib/assets/mauer1.png
    - lib/assets/mauer2.png
    - lib/assets/mauer3.png
    - lib/assets/mauer4.png
    - lib/assets/mauer.png
    - lib/assets/ma1.jpg
    - lib/assets/ma2.jpg
    - lib/assets/ma3.jpg
    - lib/assets/ma4.jpg
    - lib/assets/ma5.jpg
    - lib/assets/ma6.jpg
    - lib/assets/ma7.jpg
    - lib/assets/ma8.jpg
    - lib/assets/ma9.jpg
    - lib/assets/ma10.jpg
    - lib/assets/china2.png
    - lib/assets/chongqing1.png
    - lib/assets/chongqing4.png
    - lib/assets/china5.png
    - lib/assets/aben1.png
    - lib/assets/aben2.png
    - lib/assets/menschen2.png
    - lib/assets/ge1.png
    - lib/assets/xinli.jpg
    - lib/assets/xinli1.png
    - lib/assets/xinli2.png
    - lib/assets/xinli3.png
    - lib/assets/xinli4.png
    - lib/assets/xinli5.png
    - lib/assets/xinli6.png
    - lib/assets/xinli7.jpg
    - lib/assets/d8.png
    - lib/assets/d9.png
    - lib/assets/d10.png
    - lib/assets/a5.png
    - lib/assets/a6.png
    - lib/assets/d9.jpg
    - lib/assets/ff.mp4
    - lib/assets/ss.mp4
    - lib/assets/mm.mp4
    - lib/assets/11.mp4
    - lib/assets/12.mp4
    - lib/assets/ee.mp4
    - lib/assets/xx.mp4
    
 
   
    
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
